# EINS Feature Calculation

## Import Libraries

In [1]:
# Import libraries
import pandas as pd
import datetime
import numpy as np

## Import Data

In [2]:
# Read the compiled reports and create each sheet as a dataframe
file_name = "../../Random_Generation/Outputs/compiled_EINS_reports.xlsx"

req_criteria_df = pd.read_excel(file_name, sheet_name='Request Criteria')
search_rec_df = pd.read_excel(file_name, sheet_name='Search Record')
details_of_company_df = pd.read_excel(file_name, sheet_name='Details of Company')
capital_structure_df = pd.read_excel(file_name, sheet_name='Capital Structure')
charges_df = pd.read_excel(file_name, sheet_name='Charges')
auditors_df = pd.read_excel(file_name, sheet_name='Auditors')
officers_auth_rep_df = pd.read_excel(file_name, sheet_name='Officers Auth. Rep')
shareholders_df = pd.read_excel(file_name, sheet_name='Shareholders')
compliance_record_df = pd.read_excel(file_name, sheet_name='Compliance Record')
financial_data_df = pd.read_excel(file_name, sheet_name='Financial Data')
key_ratios_df = pd.read_excel(file_name, sheet_name='Key Ratios')
analysis_df = pd.read_excel(file_name, sheet_name='Analysis')
wos_oc_df = pd.read_excel(file_name, sheet_name='Writ of Sum. Org. Claim')
winding_up_df = pd.read_excel(file_name, sheet_name='Winding Up')
os_oa_op_om_df = pd.read_excel(file_name, sheet_name='OS OA OP OM')
add_exp_prop_info_df = pd.read_excel(file_name,  sheet_name='Add Exp Prop. Info')
accreditations_df = pd.read_excel(file_name, sheet_name='Accreditations')
fin_rel_search_count_df = pd.read_excel(file_name, sheet_name='Financial Related Search Count')
comm_rel_search_count_df = pd.read_excel(file_name, sheet_name='Commercial Related Search Count')
leg_rel_search_count_df = pd.read_excel(file_name, sheet_name='Legal Related Search Count')

## Pre-Process Data

In [3]:
# Convert prices to integers
def price_to_float(price_series):
    for i in range(len(price_series)):
        price_series[i] = int(price_series[i][7:])
    return price_series
wos_oc_df['amount'] = price_to_float(wos_oc_df['amount'])
winding_up_df['amount'] = price_to_float(winding_up_df['amount'])
os_oa_op_om_df['amount'] = price_to_float(os_oa_op_om_df['amount'])

C:\Users\brian\AppData\Local\Temp\ipykernel_12064\2976080378.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  price_series[i] = int(price_series[i][7:])

In [4]:
# Convert dates to datetime.date objects
details_of_company_df["registration_date"] = pd.to_datetime(details_of_company_df["registration_date"]).dt.date
details_of_company_df['date_of_name_change'] = pd.to_datetime(details_of_company_df['date_of_name_change']).dt.date
officers_auth_rep_df['date_of_appointment'] = pd.to_datetime(officers_auth_rep_df['date_of_appointment']).dt.date
charges_df['date_of_charge'] = pd.to_datetime(charges_df['date_of_charge']).dt.date
wos_oc_df['date_of_filling'] = pd.to_datetime(wos_oc_df['date_of_filling']).dt.date
winding_up_df['date_of_filling'] = pd.to_datetime(winding_up_df['date_of_filling']).dt.date
os_oa_op_om_df['date_of_filling'] = pd.to_datetime(os_oa_op_om_df['date_of_filling']).dt.date

In [5]:
# Calculate days since today
wos_oc_df["months_since_filling"] = list(map(lambda x: (datetime.date.today().year - x.year)*12 + datetime.date.today().month - x.month, wos_oc_df["date_of_filling"]))
winding_up_df["months_since_filling"] = list(map(lambda x: (datetime.date.today().year - x.year)*12 + datetime.date.today().month - x.month, winding_up_df["date_of_filling"]))
os_oa_op_om_df["months_since_filling"] = list(map(lambda x: (datetime.date.today().year - x.year)*12 + datetime.date.today().month - x.month, os_oa_op_om_df["date_of_filling"]))

## Feature Calculation (on one EINS report)

In [6]:
# Test on one EINS report
entity_no = req_criteria_df["requested_entity_id"].iloc[0]
searchYear = 2023

In [7]:
# Preview Details of Company dataframe
details_of_company_df.head()

,entity_name,entity_id,registration_date,country_or_region_of_incorporation_or_registration,date_of_name_change,former_name,effective_date_of_former_name,company_type,registered_office_address,date_of_address_change,principal_activities,status,status_date,Section,Division,Group,Class,Sub-Class
0,MOONLIGHT WOOD INTERNATIONAL CORP,01280320E,2022-06-27,MALAYSIA,2022-09-11,MOONLIGHT WOOD INTERNATIONAL CORP,2022/07/03,UNLIMITED PRIVATE COMPANY,MILTON HAWKWAY AVENUE #8-14 SINGAPORE 713525,2022/11/05,Retail sale of health supplements (47214),LIVE,2022/07/05,WHOLESALE AND RETAIL TRADE,RETAIL TRADE,"RETAIL SALE OF FOOD, BEVERAGES AND TOBACCO IN ...",Retail Sale of Food in Specialised Stores,Retail sale of health supplements
1,MOONLIGHT PLASTIC CENTRAL PTE LIMITED,01879010F,2016-09-02,SINGAPORE,2021-10-16,MOONLIGHT PLASTIC CENTRAL PTE LIMITED,2016/11/18,UNLIMITED PRIVATE COMPANY,JURONG MAISON #7-22 SINGAPORE 637491,2021/04/26,Retail sale of handphones and peripheral equip...,LIVE,2021/11/17,WHOLESALE AND RETAIL TRADE,RETAIL TRADE,RETAIL SALE OF INFORMATION AND COMMUNICATIONS ...,"Retail Sale of Computers, Peripheral Equipment...",Retail sale of handphones and peripheral equip...
2,MIDNIGHT METAL INTERNATIONAL CORP,07220850M,2001-04-22,MALAYSIA,2003-02-27,MIDNIGHT METAL INTERNATIONAL CORP,2002/12/15,PUBLIC COMPANY LIMITED BY SHARES,PASIR RIS MATERSON #1-47 SINGAPORE 664697,2014/10/17,"Preservation of historical sites, buildings, a...",IN LIQUIDATION,2018/12/23,"ARTS, ENTERTAINMENT AND RECREATION","LIBRARIES, ARCHIVES, MUSEUMS AND OTHER CULTURA...","LIBRARIES, ARCHIVES, MUSEUMS AND OTHER CULTURA...",Museums Activities and Operation of Historical...,"Preservation of historical sites, buildings, a..."
3,SUNSET METAL INTERNATIONAL CORP,11557137X,2001-12-15,VIETNAM,2003-09-18,SUNSET METAL INTERNATIONAL CORP,2002/06/27,UNLIMITED PRIVATE COMPANY,WESTWORD MATERSON #22-43 SINGAPORE 102641,2022/02/14,"Wholesale of industrial, construction and rela...",IN RECEIVERSHIP,2021/08/30,WHOLESALE AND RETAIL TRADE,WHOLESALE TRADE,"WHOLESALE OF MACHINERY, EQUIPMENT AND SUPPLIES","Wholesale of Industrial, Construction and Rela...","Wholesale of industrial, construction and rela..."
4,DAWN PLASTIC REGIONAL PTE LIMITED,11955614L,2019-03-22,VIETNAM,2020-11-03,DAWN PLASTIC REGIONAL PTE LIMITED,2019/08/11,EXEMPT PRIVATE COMPANY,MILTON HAWKWAY MAISON #20-2 SINGAPORE 400137,2019/08/31,International cruise services (50011),UNDER JUDICIAL MANAGEMENT,2019/04/04,TRANSPORTATION AND STORAGE,WATER TRANSPORT,WATER TRANSPORT,Passenger Water Transport,International cruise services

In [19]:
# Obtain credit history duration, country, and days since change of name
companyCreditHistoryDuration = ( datetime.date.today() - (details_of_company_df.loc[details_of_company_df["entity_id"]==entity_no, "registration_date"].values[0])).days
countryOrRegionOfIncorporationOrRegistration = details_of_company_df[(details_of_company_df["entity_id"]==entity_no)]["country_or_region_of_incorporation_or_registration"].values[0]
daysSinceChangeOfNameOfCompany = (datetime.date.today() - (details_of_company_df[(details_of_company_df['entity_id']==entity_no)]['date_of_name_change'].values[0])).days

print("companyCreditHistoryDuration: ", companyCreditHistoryDuration)
print("countryOrRegionOfIncorporationOrRegistration: ", countryOrRegionOfIncorporationOrRegistration)
print("daysSinceChangeOfNameOfCompany: ", daysSinceChangeOfNameOfCompany)

companyCreditHistoryDuration:  287
countryOrRegionOfIncorporationOrRegistration:  MALAYSIA
daysSinceChangeOfNameOfCompany:  211

In [20]:
# Retrieve principal activity of business
ssic_mapper = pd.read_csv("../../Dataset/ssic_data/ssic_mapping.csv", dtype=str)
companyPrincipalActivitySubClassCode = details_of_company_df[(details_of_company_df["entity_id"]==entity_no)]["principal_activities"].values[0][-6:-1]
ssic_lookup = ssic_mapper[ssic_mapper[ssic_mapper.columns[5]]==companyPrincipalActivitySubClassCode]

if len(ssic_lookup) != 0:
    companyPrincipalActivitySubClass = ssic_lookup["Sub-Class"].iloc[0]
    companyPrincipalActivityClass = ssic_lookup["Class"].iloc[0]
    companyPrincipalActivityGroup = ssic_lookup["Group"].iloc[0]
    companyPrincipalActivityDivision = ssic_lookup["Division"].iloc[0]
    companyPrincipalActivitySection = ssic_lookup["Section"].iloc[0]
else:
    companyPrincipalActivitySubClass = None
    companyPrincipalActivityClass = None
    companyPrincipalActivityGroup = None
    companyPrincipalActivityDivision = None
    companyPrincipalActivitySection = None

print("companyPrincipalActivitySubClass: ", companyPrincipalActivitySubClass)
print("companyPrincipalActivityClass: ", companyPrincipalActivityClass)
print("companyPrincipalActivityGroup: ", companyPrincipalActivityGroup)
print("companyPrincipalActivityDivision: ", companyPrincipalActivityDivision)
print("companyPrincipalActivitySection: ", companyPrincipalActivitySection)

companyPrincipalActivitySubClass:  Retail sale of health supplements
companyPrincipalActivityClass:  Retail Sale of Food in Specialised Stores
companyPrincipalActivityGroup:  RETAIL SALE OF FOOD, BEVERAGES AND TOBACCO IN SPECIALISED STORES
companyPrincipalActivityDivision:  RETAIL TRADE
companyPrincipalActivitySection:  WHOLESALE AND RETAIL TRADE

In [46]:
# Preview Capital Structure dataframe
capital_structure_df.head()

,entity_id,issued_ordinary_no_of_shares,currency_of_issued_ordinary,amount_of_issued_ordinary,paid_up_ordinary_no_of_shares,currency_of_paid_up_ordinary,amount_of_paid_up_ordinary,paid_up_preference_no_of_shares,currency_of_paid_up_preference,amount_of_paid_up_preference,paid_up_others_no_of_shares,currency_of_paid_up_others,amount_of_paid_up_others
0,01280320E,93207,"SINGAPORE, DOLLARS",481711,9002441,"SINGAPORE, DOLLARS",7776140,7573852,"SINGAPORE, DOLLARS",633994,2789898,"SINGAPORE, DOLLARS",1792019
1,01879010F,8503898,"SINGAPORE, DOLLARS",708761,9047543,"SINGAPORE, DOLLARS",6539632,9635774,"SINGAPORE, DOLLARS",3998398,930392,"SINGAPORE, DOLLARS",1788057
2,07220850M,7073286,"SINGAPORE, DOLLARS",3423004,5414281,"SINGAPORE, DOLLARS",1251186,7893522,"SINGAPORE, DOLLARS",2211989,8354107,"SINGAPORE, DOLLARS",6137888
3,11557137X,4956052,"SINGAPORE, DOLLARS",334034,6599436,"SINGAPORE, DOLLARS",9633310,1898157,"SINGAPORE, DOLLARS",8484018,1965559,"SINGAPORE, DOLLARS",5618824
4,11955614L,1499745,"SINGAPORE, DOLLARS",4517669,9267854,"SINGAPORE, DOLLARS",8283785,1889555,"SINGAPORE, DOLLARS",6190617,5154991,"SINGAPORE, DOLLARS",8809924

In [47]:
# Calculate price of shares and total shares
priceOfCompanyIssuedOrdinary = capital_structure_df[(capital_structure_df["entity_id"]==entity_no)]["amount_of_issued_ordinary"].values[0] / capital_structure_df[(capital_structure_df["entity_id"]==entity_no)]["issued_ordinary_no_of_shares"].values[0]
totalShares = capital_structure_df[(capital_structure_df['entity_id']==entity_no)]['issued_ordinary_no_of_shares'].values[0]

print("priceOfCompanyIssuedOrdinary: ", priceOfCompanyIssuedOrdinary)
print("totalShares: ", totalShares)

priceOfCompanyIssuedOrdinary:  5.168184792987651
totalShares:  93207

In [48]:
# Preview Shareholders dataframe
shareholders_df.head()

,shareholder_name,shareholder_id,nationality_or_citizenship,shareholder_address,date_of_change_of_address,type_of_shares,no_of_shares,currency,entity_id
0,SUNSET AIR CENTRAL CORP,W0V5S87M,MALAYSIA,CHANGI BROADWAY #22-3 VIETNAM 632316,2022/08/04,CONVERTIBLE PREFERENCE,24832003,"SINGAPORE, DOLLARS",01280320E
1,SUNSHINE WATER PREFECTURE PTE LIMITED,LA971UU7,MALAYSIA,JURONG AVENUE #8-31 NORWAY 931019,-,PREFERENCE,41572859,"SINGAPORE, DOLLARS",01280320E
2,MOONLIGHT RIVER STATE CORP,516OYPPC,UK,WESTWORD DRIVE #16-32 ITALY 942180,-,TREASURY,91643602,"SINGAPORE, DOLLARS",01280320E
3,SUNSET AIR REGIONAL PTE LIMITED,I9CK3ZEU,SINGAPORE,PASIR RIS MAISON #1-40 MALAYSIA 208157,-,TREASURY,72337706,"SINGAPORE, DOLLARS",01280320E
4,SUNSHINE AIR COAST ENTERPRISE,LCVJNSCW,SINGAPORE,JURONG BOULEVARD #30-18 VIETNAM 838589,2017/04/08,TREASURY,54497949,"SINGAPORE, DOLLARS",01879010F

In [49]:
# Calculate number of shares owned by shareholders, number of shareholders, and number of shareholders holding > 20% shares
numSharesOwnedByShareholders = shareholders_df[(shareholders_df["entity_id"]==entity_no)]["no_of_shares"].sum()
numShareholders = shareholders_df[(shareholders_df["entity_id"]==entity_no)]["shareholder_name"].count()
numShareholdersWithMoreThan20PercentShares = len(shareholders_df[(shareholders_df["entity_id"]==entity_no) & (shareholders_df["no_of_shares"] >= 0.2*totalShares)])

print("numSharesOwnedByShareholders: ", numSharesOwnedByShareholders)
print("numShareholders: ", numShareholders)
print("numShareholdersWithMoreThan20PercentShares: ", numShareholdersWithMoreThan20PercentShares)

numSharesOwnedByShareholders:  230386170
numShareholders:  4
numShareholdersWithMoreThan20PercentShares:  4

In [50]:
# Preview Financial Data dataframe
financial_data_df.head()

,entity_id,current_fye,previous_fye,currency,current_fye_revenue,previous_fye_revenue,percentage_change_revenue,current_fye_profit_after_tax,previous_fye_profit_after_tax,percentage_change_profit_after_tax,current_fye_shareholders_fund,previous_fye_shareholders_fund,percentage_change_shareholders_fund
0,01280320E,31/12/2022,31/12/2021,"SINGAPORE, DOLLARS",23018656383,31924753752,-27.90,22762166789,30980087731,-26.53,22111125813,30975074193,-28.62
1,01879010F,31/12/2022,31/12/2021,"SINGAPORE, DOLLARS",36943000625,11706607790,215.57,36514751225,11167974367,226.96,36000775176,10765630973,234.40
2,07220850M,31/12/2022,31/12/2021,"SINGAPORE, DOLLARS",16700701493,74005635226,-77.43,15753693653,73051798417,-78.43,15766122970,73018559346,-78.41
3,11557137X,31/12/2022,31/12/2021,"SINGAPORE, DOLLARS",11736978820,55765623418,-78.95,11291602721,55515738181,-79.66,10801448739,54830846291,-80.30
4,11955614L,31/12/2022,31/12/2021,"SINGAPORE, DOLLARS",22982804961,44487608259,-48.34,22029407314,43882177865,-49.80,22028382397,43567423561,-49.44

In [51]:
# Calculate revenue, profit, shareholders fund, and their respective increment from the previous year
amountOfRevenue = financial_data_df[financial_data_df["entity_id"]==entity_no]["current_fye_revenue"].values[0]
increasedRevenueFromPreviousYear = amountOfRevenue - financial_data_df[financial_data_df["entity_id"]==entity_no]["previous_fye_revenue"].values[0]
amountOfProfitAfterTax = financial_data_df[financial_data_df["entity_id"]==entity_no]["current_fye_profit_after_tax"].values[0]
increasedProfitFromPreviousYear = amountOfProfitAfterTax -financial_data_df[financial_data_df["entity_id"]==entity_no]["previous_fye_profit_after_tax"].values[0]
amountOfShareholdersFund = financial_data_df[financial_data_df["entity_id"]==entity_no]["current_fye_shareholders_fund"].values[0]
increasedShareholdersFundFromPreviousYear = amountOfShareholdersFund - financial_data_df[financial_data_df["entity_id"]==entity_no]["previous_fye_shareholders_fund"].values[0]

print("amountOfRevenue: ", amountOfRevenue)
print("increasedRevenueFromPreviousYear: ", increasedRevenueFromPreviousYear)
print("amountOfProfitAfterTax: ", amountOfProfitAfterTax)
print("increasedProfitFromPreviousYear: ", increasedProfitFromPreviousYear)
print("amountOfShareholdersFund: ", amountOfShareholdersFund)
print("increasedShareholdersFundFromPreviousYear: ", increasedShareholdersFundFromPreviousYear)

amountOfRevenue:  23018656383
increasedRevenueFromPreviousYear:  -8906097369
amountOfProfitAfterTax:  22762166789
increasedProfitFromPreviousYear:  -8217920942
amountOfShareholdersFund:  22111125813
increasedShareholdersFundFromPreviousYear:  -8863948380

In [52]:
# Preview Key Ratios dataframe
key_ratios_df.head()

,entity_id,current_fye,previous_fye,current_fye_profit_margin,previous_fye_profit_margin,current_fye_liquidity_times,previous_fye_liquidity_times,current_fye_debt_times,previous_fye_debt_times
0,01280320E,31/12/2022,31/12/2021,4.55%,2.93%,0.52,2.78,1.85,1.45
1,01879010F,31/12/2022,31/12/2021,3.52%,4.38%,2.95,1.33,2.39,1.99
2,07220850M,31/12/2022,31/12/2021,2.82%,4.12%,2.59,2.04,0.82,2.80
3,11557137X,31/12/2022,31/12/2021,4.62%,2.2%,2.68,1.20,0.30,0.92
4,11955614L,31/12/2022,31/12/2021,2.8%,4.69%,0.10,1.00,0.69,1.61

In [53]:
# Calculate profit margin, liquidity and debt ratio, and their respective increment from the previous year
companyProfitMargin = float(key_ratios_df[key_ratios_df["entity_id"]==entity_no]["current_fye_profit_margin"].values[0].strip('%'))/100
increasedProfitMarginFromPreviousYear = companyProfitMargin - float(key_ratios_df[key_ratios_df["entity_id"]==entity_no]["previous_fye_profit_margin"].values[0].strip('%'))/100

companyLiquidity = key_ratios_df[key_ratios_df["entity_id"]==entity_no]["current_fye_liquidity_times"].values[0]
increasedLiquidityFromPreviousYear = companyLiquidity - key_ratios_df[key_ratios_df["entity_id"]==entity_no]["previous_fye_liquidity_times"].values[0]

companyDebtRatio = key_ratios_df[key_ratios_df["entity_id"]==entity_no]["current_fye_debt_times"].values[0]
increasedDebtRatioFromPreviousYear = companyDebtRatio - key_ratios_df[key_ratios_df["entity_id"]==entity_no]["previous_fye_debt_times"].values[0]

print("companyProfitMargin: ", companyProfitMargin)
print("increasedProfitMarginFromPreviousYear: ", increasedProfitMarginFromPreviousYear)

print("companyLiquidity: ", companyLiquidity)
print("increasedLiquidityFromPreviousYear: ", increasedLiquidityFromPreviousYear)

print("companyDebtRatio: ", companyDebtRatio)
print("increasedDebtRatioFromPreviousYear: ", increasedDebtRatioFromPreviousYear)

companyProfitMargin:  0.0455
increasedProfitMarginFromPreviousYear:  0.016199999999999996
companyLiquidity:  0.52
increasedLiquidityFromPreviousYear:  -2.26
companyDebtRatio:  1.85
increasedDebtRatioFromPreviousYear:  0.40000000000000013

In [54]:
# Preview Analysis dataframe
analysis_df.head()

,entity_id,fye,company_level_revenue_growth,industry_median_revenue_growth,company_level_return_on_assets,industry_median_return_on_assets,company_level_total_asset_turnover,industry_median_total_asset_turnover,company_level_net_profit_margin,industry_median_net_profit_margin
0,01280320E,2022,51.15%,19.92%,4.49%,4.19%,13.68%,14.36%,4.12%,4.65%
1,01879010F,2022,43.23%,11.2%,2.33%,4.47%,26.2%,9.2%,2.48%,4.6%
2,07220850M,2022,30.28%,14.81%,2.91%,4.83%,28.89%,12.73%,4.53%,3.11%
3,11557137X,2022,48.92%,18.81%,4.52%,2.51%,20.18%,4.93%,4.57%,3.23%
4,11955614L,2022,23.92%,29.34%,2.92%,3.32%,16.19%,2.18%,2.0%,2.48%

In [55]:
# Calculate return on assets, totl asset turnover, net profit margin and revenue growth, and their respective comparisons against the industry median
companyReturnOnAssets = float(analysis_df[(analysis_df["entity_id"]==entity_no)]["company_level_return_on_assets"].values[0].strip('%'))/100
companyReturnOnAssetsAgainstIndustryMedian = companyReturnOnAssets - float(analysis_df[(analysis_df["entity_id"]==entity_no)]["industry_median_return_on_assets"].values[0].strip('%'))/100

companyTotalAssetTurnover = float(analysis_df[(analysis_df["entity_id"]==entity_no)]["company_level_total_asset_turnover"].values[0].strip('%'))/100
companyTotalAssetTurnoverAgainstIndustryMedian = companyTotalAssetTurnover - float(analysis_df[(analysis_df["entity_id"]==entity_no)]["industry_median_total_asset_turnover"].str.strip('%'))

companyNetProfitMarginAgainstIndustryMedian = companyProfitMargin - float(analysis_df[analysis_df["entity_id"]==entity_no]["industry_median_net_profit_margin"].values[0].strip('%'))/100

companyRevenueGrowth = float(analysis_df[(analysis_df["entity_id"]==entity_no)]["company_level_revenue_growth"].values[0].strip('%'))/100
companyRevenueGrowthAgainstIndustryMedian = companyRevenueGrowth - float(analysis_df[(analysis_df["entity_id"]==entity_no)]["industry_median_revenue_growth"].values[0].strip('%'))/100

print("companyReturnOnAssets: ", companyReturnOnAssets)
print("companyReturnOnAssetsAgainstIndustryMedian: ", companyReturnOnAssetsAgainstIndustryMedian)

print("companyTotalAssetTurnover: ", companyTotalAssetTurnover)
print("companyTotalAssetTurnoverAgainstIndustryMedian: ", companyTotalAssetTurnoverAgainstIndustryMedian)

print("companyNetProfitMarginAgainstIndustryMedian: ", companyNetProfitMarginAgainstIndustryMedian)

print("companyRevenueGrowth: ", companyRevenueGrowth)
print("companyRevenueGrowthAgainstIndustryMedian: ", companyRevenueGrowthAgainstIndustryMedian)

companyReturnOnAssets:  0.0449
companyReturnOnAssetsAgainstIndustryMedian:  0.0029999999999999957
companyTotalAssetTurnover:  0.1368
companyTotalAssetTurnoverAgainstIndustryMedian:  -14.2232
companyNetProfitMarginAgainstIndustryMedian:  -0.0010000000000000078
companyRevenueGrowth:  0.5115
companyRevenueGrowthAgainstIndustryMedian:  0.3122999999999999

In [56]:
# Preview Charges dataframe
charges_df.head()

,charge_id,date_of_charge,chargee,amount_secured_and_currency,status,entity_id
0,C202226710,2022-12-25,BANK NAME,"78338848 SINGAPORE, DOLLARS",CURRENT,01280320E
1,C202293607,2022-12-16,BANK NAME,"36753753 SINGAPORE, DOLLARS",CURRENT,01280320E
2,C202208785,2022-07-01,BANK NAME,"20820434 SINGAPORE, DOLLARS",PARTIAL SATISFACTION AND REMAIN IN REGISTER,01280320E
3,C202291690,2022-12-01,BANK NAME,"30496530 SINGAPORE, DOLLARS",PARTIAL SATISFACTION AND REMAIN IN REGISTER,01280320E
4,C202278716,2022-09-05,BANK NAME,"2538239 SINGAPORE, DOLLARS",PARTIAL SATISFACTION AND REMAIN IN REGISTER,01280320E

In [57]:
# Calculate number of existing loans and length of banking relationship
numExistingLoans = len(charges_df[(charges_df["entity_id"]==entity_no) &(charges_df["status"]!="COMPLETE")])
lengthOfBankingRelationship = (datetime.date.today() - charges_df.loc[charges_df['entity_id']==entity_no, 'date_of_charge'].values[0]).days

print("numExistingLoans: ", numExistingLoans)
print("lengthOfBankingRelationship: ", lengthOfBankingRelationship)

numExistingLoans:  5
lengthOfBankingRelationship:  105

In [58]:
# Preview Auditors dataframe
auditors_df.head()

  auditor_name date_of_appointment  entity_id
0         KPMG          2022/12/29  01280320E
1          PWC          2020/06/10  01879010F
2     DELOITTE          2022/12/15  07220850M
3     DELOITTE          2012/08/01  11557137X
4           EY          2020/11/06  11955614L

In [59]:
# Obtain the auditor
auditor = auditors_df[(auditors_df["entity_id"]==entity_no)]["auditor_name"].values[0]
print("auditor:", auditor)

auditor: KPMG

In [60]:
# Preview Officers Auth Rep dataframe
officers_auth_rep_df.head()

,employee_name,employee_id,employee_address,date_of_change_of_address,nationality_or_citizenship,date_of_appointment,position_held,entity_id
0,CHARLES NG ABEL,V134XXXXO,MILTON HAWKWAY MAISON #5-22 US 936467,2022/12/13,THAILAND,2022-10-26,ALTERNATE DIRECTOR,01280320E
1,SARA NG ABEL,Y206XXXXM,PUNGGOL DRIVE #19-24 VIETNAM 350627,-,MALAYSIA,2021-04-12,DIRECTOR,01879010F
2,MAY MEI NAQUILA,O444XXXXT,CALDECOTT BOULEVARD #21-33 ITALY 771153,-,MALAYSIA,2020-02-12,SHAREHOLDER,01879010F
3,CHARLES HOW ABEL,M682XXXXX,PASIR RIS DRIVE #5-7 UK 955759,2022/05/20,UK,2019-01-30,SHAREHOLDER,01879010F
4,SUSAN BIN NAQUILA,N815XXXXX,MILTON HAWKWAY DRIVE #24-50 NORWAY 632120,-,MALAYSIA,2021-04-08,DIRECTOR,01879010F

In [61]:
# Obtain the officer's nationality and current duration of appointment
officerNationality = officers_auth_rep_df[(officers_auth_rep_df["entity_id"]==entity_no)]["nationality_or_citizenship"].values[0]
officerAppointmentDuration = (datetime.date.today() - officers_auth_rep_df[officers_auth_rep_df['entity_id']==entity_no]['date_of_appointment'].values[0]).days

print("officerNationality:", officerNationality)
print("officerAppointmentDuration:", officerAppointmentDuration)

officerNationality: THAILAND
officerAppointmentDuration: 165

In [62]:
# Preview WOS/OC dataframe
wos_oc_df.head()

,sn,court_type,case_no,year,date_of_filling,plaintiff,case_status,date_of_case_status,case_status_remarks,plaintiff_status,...,date_of_defendant_status,amount,last_updated,main_cause,entity_id,main_cause_category,case_status_category,plaintiff_status_category,defendant_status_category,months_since_filling
0,1,MC / OC,3980,2022,2022-08-05,DAWN WATER PREFECTURE ENTERPRISE,SUBSTITUTED SERVICE APPLN.,2022/08/28,PETITION DISMISSED,FINAL JUDGMENT - JUDGMENT -,...,2022/08/19,18179000,2022/10/27,Others($18541.85),01280320E,Others,Others,Judgement,Discharge Notice,8
1,2,DC / OC,3274,2022,2022-06-30,DUSK METAL REGIONAL ENTERPRISE,NOTICE OF DISCHARGE UNDER SECTION 125 (3),2022/07/14,NOTICE OF DISCHARGE UNDER SECTION 125,DEFAULT JUDGMENT - O13,...,2022/07/21,16156000,2022/12/21,WRIT OF SEIZURE AND SALE MC 000000000018673/20...,01280320E,Others,Discharged,Judgement,Others,10
2,1,DC / OC,1551,2018,2018-11-10,DAWN METAL CENTRAL PTE LIMITED,CONCLUDED (09-JUN-2010),2020/06/02,CONCLUDED (24-JUN-2004),DEFAULT JUDGMENT,...,2020/11/30,17966000,2023/01/07,Contract-Others(Breach of Share Purchase Agree...,01879010F,Contracts,Concluded,Judgement,Others,53
3,2,MC / WOS,6720,2017,2017-03-09,SUNSHINE WATER INTERNATIONAL ENTERPRISE,NOTICE OF DISCHARGE UNDER SECTION 125A,2017/08/29,NOTICE OF DISCHARGE UNDER SECTIOIN 123A,CASE STRUCK OUT,...,2017/09/18,19471000,2018/05/02,BY SPECIAL RESOLUTION,01879010F,Others,Discharged,Judgement,Others,73
4,3,SC / OC,7264,2020,2020-05-11,MIDNIGHT AIR COAST PTE LIMITED,CONCLUDED (09-NOV-2012),2020/11/27,CONCLUDED (28-JUL-2003),FINAL JUDGMENT - JUDGMENT -,...,2020/10/15,26534000,2022/07/08,Contract-Others(Artist Performance),01879010F,Contracts,Concluded,Judgement,Others,35

In [63]:
# Calculate pending, concluded and total WOS and OC, as well as the totals against revenues

totalPendingWOSAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) &
    ("WOS" in wos_oc_df["court_type"]) &
    (wos_oc_df["case_status"]=="PENDING")
    ]["amount"].sum()

totalConcludedWOSAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) & 
    ("WOS" in wos_oc_df["court_type"]) &
    ("CONCLUDED" in wos_oc_df["case_status"])
    ]["amount"].sum()

totalPendingOCAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) &
    ("OC" in wos_oc_df["court_type"]) &
    (wos_oc_df["case_status"]=="PENDING")
    ]["amount"].sum()

totalConcludedOCAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) &
    ("OC" in wos_oc_df["court_type"]) &
    ("CONCLUDED" in wos_oc_df["case_status"])
    ]["amount"].sum()

totalWOSAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) &
    ("WOS" in wos_oc_df["court_type"])
    ]["amount"].sum()

totalOCAmount = wos_oc_df[
    (wos_oc_df["entity_id"]==entity_no) &
    ("WOS" in wos_oc_df["court_type"])
    ]["amount"].sum()

totalWOSAndOCAmount = float(totalWOSAmount) + float(totalOCAmount)
totalWOSAmountAgainstRevenue = float(totalWOSAmount) / float(amountOfRevenue)
totalOCAmountAgainstRevenue = float(totalOCAmount) / float(amountOfRevenue)
totalWOSAndOCAgainstRevenue = float(totalWOSAndOCAmount) / float(amountOfRevenue)


print("totalPendingWOSAmount:", totalPendingWOSAmount)
print("totalConcludedWOSAmount:", totalConcludedWOSAmount)

print("totalPendingOCAmount:", totalPendingOCAmount)
print("totalConcludedOCAmount:", totalConcludedOCAmount)

print("totalWOSAmount:", totalWOSAmount)
print("totalOCAmount:", totalOCAmount)
print("totalWOSAndOCAmount:", totalWOSAndOCAmount)

print("totalWOSAmountAgainstRevenue:", totalWOSAmountAgainstRevenue)
print("totalOCAmountAgainstRevenue:", totalOCAmountAgainstRevenue)
print("totalWOSAndOCAgainstRevenue:", totalWOSAndOCAgainstRevenue)

totalPendingWOSAmount: 0
totalConcludedWOSAmount: 0
totalPendingOCAmount: 0
totalConcludedOCAmount: 0
totalWOSAmount: 0
totalOCAmount: 0
totalWOSAndOCAmount: 0.0
totalWOSAmountAgainstRevenue: 0.0
totalOCAmountAgainstRevenue: 0.0
totalWOSAndOCAgainstRevenue: 0.0

In [64]:
# Calculate business litigation counts and amounts across court types, number of months, status, and cause

for court_type in ["MC / WOS", "DC / WOS", "SC / WOS", "MC / OC", "DC / OC", "SC / OC"]:
    for num_months in [3, 6, 9, 12, 24, 36]:
        for status in ["Concluded", "Bankruptcy Related", "Discharged", "Others"]:
            for cause in ["Negligence & Accidents", "Financials", "Contracts", "Provision of Goods and Services", "Others"]:
                
                wos_oc_df[
                    (wos_oc_df['entity_id'] == entity_no) &
                    (wos_oc_df["court_type"] == court_type) &
                    (wos_oc_df['months_since_filling']) &
                    (status in wos_oc_df["case_status_category"]) &
                    (cause in wos_oc_df["main_cause_category"]) 
                ]["amount"].sum()

                wos_oc_df[
                    (wos_oc_df['entity_id'] == entity_no) &
                    (wos_oc_df["court_type"] == court_type) &
                    (wos_oc_df['months_since_filling']) &
                    (status in wos_oc_df["case_status_category"]) &
                    (cause in wos_oc_df["main_cause_category"]) 
                ]["amount"].count()

In [65]:
# Preview Winding Up dataframe
winding_up_df.head()

,type,case_no,year,date_of_filling,other_party_name,case_status,date_of_case_status,other_party_status,date_of_other_party_status,defendant_status,date_of_defendant_status,amount,last_updated,entity_id,case_status_category,other_party_status_category,defendant_status_category,months_since_filling
0,WINDING UP,1033,2022,2022-11-30,SUNSHINE AIR PREFECTURE PTE LIMITED,NOTICE OF DISCHARGING UNDER SECTION 125(3),2022/12/01,GUOK CHIN KIAT FRANCIS,2022/12/01,APPEAL ALLOWED IN PART AND DISMISSED IN PART,2022/12/08,11809641,2022/12/12,01280320E,Discharged,Others,Others,5
1,WINDING UP,7080,2022,2022-07-14,SUNSHINE GREENYARN CENTRAL CORP,CONCLUDED (11-DEC-2013),2022/07/17,NOTICE OF ANNULMENT UNDER SECTION 123A,2022/10/04,FINAL JUDGMENT WITHOUT TRIAIL,2022/07/19,37959503,2022/10/27,01280320E,Concluded,Annulment,Judgement,9
2,WINDING UP,3708,2022,2022-09-16,MIDNIGHT RIVER REGIONAL PTE LIMITED,CONCLUDED (06-JUN-2008),2022/11/04,NO DOC FILED FOR MORE THAN 1 YEAR,2022/10/06,JUDGMENT(EFS),2022/10/20,9598501,2022/11/06,01280320E,Concluded,Others,Judgement,7
3,WINDING UP,8325,2022,2022-08-24,SUNSET AIR STATE PTE LIMITED,CONCLUDED (12-JUN-2013),2022/09/12,NOTICE OF DISCHARGE UNDER SECTION 123(3),2022/08/27,CONCLUDED,2022/09/15,19951564,2022/10/16,01280320E,Concluded,Discharge Notice,Others,8
4,WINDING UP,1133,2022,2022-09-30,MIDNIGHT WATER COAST PTE LIMITED,NO ORDER,2022/11/02,BANKRUPTCY APPLICATION APPLICATION,2022/10/24,SET ASIDE,2022/10/11,25797265,2022/12/26,01280320E,Others,Bankruptcy Related,Others,7

In [66]:
# Calculate pending, concluded and total winding up, as well as the totals against revenues

totalConcludedWindingUpAmount = winding_up_df[
    (winding_up_df["entity_id"]==entity_no) &
    (winding_up_df["type"]=="WINDING UP") &
    ("CONCLUDED" in winding_up_df["case_status"]) ]["amount"].sum()

totalPendingWindingUpAmount = winding_up_df[
    (winding_up_df["entity_id"]==entity_no) &
    (winding_up_df["type"]=="WINDING UP") &
    ("PENDING" in winding_up_df["case_status"]) ]["amount"].sum()

totalWindingUpAmount = winding_up_df[
    (winding_up_df["entity_id"]==entity_no) &
    (winding_up_df["type"]=="WINDING UP") ]["amount"].sum()

windingUpTotalAmountAgainstRevenue = float(totalWindingUpAmount)/float(amountOfRevenue)

print("totalConcludedWindingUpAmount:", totalConcludedWindingUpAmount)
print("totalPendingWindingUpAmount:", totalPendingWindingUpAmount)
print("totalWindingUpAmount:", totalWindingUpAmount)
print("windingUpTotalAmountAgainstRevenue:", windingUpTotalAmountAgainstRevenue)

totalConcludedWindingUpAmount: 0
totalPendingWindingUpAmount: 0
totalWindingUpAmount: 105116474
windingUpTotalAmountAgainstRevenue: 0.004566577312376574

In [67]:
# Calculate winding up counts and amounts across number of months, and status

for num_months in [3, 6, 9, 12, 24, 36]:
    for status in ["Concluded", "Bankruptcy Related", "Discharged", "Others"]:
        
        winding_up_df[
            (winding_up_df['entity_id'] == entity_no) &
            (winding_up_df['months_since_filling'] < num_months) &
            (status in winding_up_df["case_status_category"])
        ]["amount"].sum()

        winding_up_df[
            (winding_up_df['entity_id'] == entity_no) &
            (winding_up_df['months_since_filling'] < num_months) &
            (status in winding_up_df["case_status_category"])
        ]["amount"].count()

In [68]:
# Preview OS/OA/OP/OM dataframe
os_oa_op_om_df.head()

,type,case_no,year,date_of_filling,other_party_name,case_status,date_of_case_status,other_party_status,date_of_other_party_status,defendant_status,date_of_defendant_status,amount,last_updated,entity_id,case_status_category,other_party_status_category,defendant_status_category,months_since_filling
0,ORIGINATING SUMMONS,8326,2022,2022-08-05,DAWN PLASTIC CENTRAL CORP,CONCLUDED (23-JUN-2006),2022/09/16,NOTICE OF ANNUMENT UNDER SECTION 123A,2022/09/17,SETTLED - BEFORE SET DOWN,2022/08/09,20431453,2022/09/20,01280320E,Concluded,Discharge Notice,Others,8
1,ORIGINATING SUMMONS,9753,2022,2022-08-14,TWILIGHT GREENYARN CENTRAL PTE LIMITED,CONCLUDED (17-MAR-2006),2022/09/15,JUDGMENT(EFS),2022/10/15,JUDGMENT 19,2022/09/03,25341249,2022/10/24,01280320E,Concluded,Judgement,Judgement,8
2,ORIGINATING SUMMONS,9276,2020,2020-08-04,MOONLIGHT PLASTIC PREFECTURE PTE LIMITED,CONCLUDED (02-APR-2012),2022/04/08,DISCONTINUED/ WITHDRAWN,2020/10/12,CONLCUDED,2020/12/12,24531343,2022/05/18,01879010F,Concluded,Others,Others,32
3,ORIGINATING SUMMONS,1338,2021,2021-07-31,DUSK WOOD STATE ENTERPRISE,FOR STAY OF BANKRUPTCY ORDER,2021/09/27,NO ORDERS MADE,2021/08/20,ADJOURNED DRS,2022/05/08,12581015,2022/05/12,01879010F,Bankruptcy Related,Others,Others,21
4,ORIGINATING SUMMONS,1278,2017,2017-12-22,SUNSET RIVER REGIONAL ENTERPRISE,CONCLUDED-CONVERTED,2020/01/31,JUDGMENT NO.,2019/04/01,DISCHARGE BY ORDER OF COURT (SECTION 124),2017/12/31,24114746,2020/07/11,01879010F,Concluded,Judgement,Discharge Notice,64

In [69]:
# Calculate pending, concluded and total OS, OA, OP, and OM, as well as the totals against revenues

totalPendingOSAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING SUMMONS") &
    ("PENDING" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalConcludedOSAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING SUMMONS") &
    ("CONCLUDED" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalOSAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING SUMMONS")]["amount"].sum()

totalOSAmountAgainstRevenue = float(totalOSAmount)/float(amountOfRevenue)


totalPendingOAAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING APPLICATIONS") &
    ("PENDING" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalConcludedOAAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING APPLICATIONS") &
    ("CONCLUDED" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalOAAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING APPLICATIONS")]["amount"].sum()

totalOAAmountAgainstRevenue = float(totalOAAmount)/float(amountOfRevenue)


totalPendingOPAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING PETITIONS") &
    ("PENDING" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalConcludedOPAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING PETITIONS") &
    ("CONCLUDED" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalOPAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING PETITIONS")]["amount"].sum()

totalOPAmountAgainstRevenue = float(totalOPAmount)/float(amountOfRevenue)


totalPendingOMAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING MOTIONS") &
    ("PENDING" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalConcludedOMAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING MOTIONS") &
    ("CONCLUDED" in os_oa_op_om_df["case_status"])]["amount"].sum()

totalOMAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no) &
    (os_oa_op_om_df["type"]=="ORIGINATING MOTIONS")]["amount"].sum()

totalOMAmountAgainstRevenue = float(totalOMAmount)/float(amountOfRevenue)


totalPendingOSOAOPOMAmount = totalPendingOSAmount + totalPendingOAAmount + totalPendingOPAmount + totalPendingOMAmount

totalConcludedOSOAOPOMAmount = totalConcludedOSAmount + totalConcludedOAAmount + totalConcludedOPAmount + totalConcludedOMAmount

totalOSOAOPOMAmount = os_oa_op_om_df[
    (os_oa_op_om_df["entity_id"]==entity_no)]["amount"].sum()

totalOSOAOPOMAmountAgainstRevenue = float(totalOSOAOPOMAmount)/ float(amountOfRevenue)


print("totalPendingOSAmount:", totalPendingOSAmount)
print("totalConcludedOSAmount:", totalConcludedOSAmount)
print("totalOSAmount:", totalOSAmount)
print("totalOSAmountAgainstRevenue:", totalOSAmountAgainstRevenue)

print("totalPendingOAAmount:", totalPendingOAAmount)
print("totalConcludedOAAmount:", totalConcludedOAAmount)
print("totalOAAmount:", totalOAAmount)
print("totalOAAmountAgainstRevenue:", totalOAAmountAgainstRevenue)

print("totalPendingOPAmount:", totalPendingOPAmount)
print("totalConcludedOPAmount:", totalConcludedOPAmount)
print("totalOPAmount:", totalOPAmount)
print("totalOPAmountAgainstRevenue:", totalOPAmountAgainstRevenue)

print("totalPendingOMAmount:", totalPendingOMAmount)
print("totalConcludedOMAmount:", totalConcludedOMAmount)
print("totalOMAmount:", totalOMAmount)
print("totalOMAmountAgainstRevenue:", totalOMAmountAgainstRevenue)

print("totalPendingOSOAOPOMAmount:", totalPendingOSOAOPOMAmount)
print("totalConcludedOSOAOPOMAmount:", totalConcludedOSOAOPOMAmount)
print("totalOSOAOPOMAmount:", totalOSOAOPOMAmount)
print("totalOSOAOPOMAmountAgainstRevenue:", totalOSOAOPOMAmountAgainstRevenue)

totalPendingOSAmount: 0
totalConcludedOSAmount: 0
totalOSAmount: 45772702
totalOSAmountAgainstRevenue: 0.0019885045086213016
totalPendingOAAmount: 0
totalConcludedOAAmount: 0
totalOAAmount: 0
totalOAAmountAgainstRevenue: 0.0
totalPendingOPAmount: 0
totalConcludedOPAmount: 0
totalOPAmount: 0
totalOPAmountAgainstRevenue: 0.0
totalPendingOMAmount: 0
totalConcludedOMAmount: 0
totalOMAmount: 0
totalOMAmountAgainstRevenue: 0.0
totalPendingOSOAOPOMAmount: 0
totalConcludedOSOAOPOMAmount: 0
totalOSOAOPOMAmount: 45772702
totalOSOAOPOMAmountAgainstRevenue: 0.0019885045086213016

In [70]:
# Calculate OS, OA, OP and OM counts and amounts across each type, number of months, and status

for orig_type in ["ORIGINATING SUMMONS", "ORIGINATING APPLICATIONS", "ORIGINATING PETITIONS", "ORIGINATING MOTIONS"]:
    for num_months in [3, 6, 9, 12, 24, 36]:
        for status in ["Concluded", "Bankruptcy Related", "Discharged", "Others"]:
            
            os_oa_op_om_df[
                (os_oa_op_om_df['entity_id'] == entity_no) &
                (os_oa_op_om_df["type"] == orig_type) &
                (os_oa_op_om_df['months_since_filling'] < num_months) &
                (status in os_oa_op_om_df["case_status_category"])
            ]["amount"].sum()

            os_oa_op_om_df[
                (os_oa_op_om_df['entity_id'] == entity_no) &
                (os_oa_op_om_df["type"] == orig_type) &
                (os_oa_op_om_df['months_since_filling'] < num_months) &
                (status in os_oa_op_om_df["case_status_category"])
            ]["amount"].count()

In [71]:
# Preview Financial Related Search Count dataframe
fin_rel_search_count_df.head()

   entity_id  year month purpose  count
0  01280320E  2022   All     All      5
1  01280320E  2022   Jan     All      1
2  01280320E  2022   Feb     All      4
3  01280320E  2022   Mar     All      0
4  01280320E  2022   Apr     All      0

In [72]:
# Preview Commercial Related Search Count dataframe
comm_rel_search_count_df.head()

   entity_id  year month purpose  count
0  01280320E  2022   All     All      4
1  01280320E  2022   Jan     All      0
2  01280320E  2022   Feb     All      0
3  01280320E  2022   Mar     All      0
4  01280320E  2022   Apr     All      1

In [73]:
# Preview Legal Related Search Count dataframe
leg_rel_search_count_df.head()

   entity_id  year month purpose  count
0  01280320E  2022   All     All      2
1  01280320E  2022   Jan     All      0
2  01280320E  2022   Feb     All      0
3  01280320E  2022   Mar     All      0
4  01280320E  2022   Apr     All      0

In [74]:
# Calculate recent year financial, commercial and legal search counts

recentYearFinancialSearchCount = fin_rel_search_count_df[
    (fin_rel_search_count_df["entity_id"]==entity_no) &
    (fin_rel_search_count_df["year"]== searchYear-1)]["count"].sum()

recentYearTradeInsuranceSearchCount = fin_rel_search_count_df[
    (fin_rel_search_count_df["entity_id"]==entity_no) &
    (fin_rel_search_count_df["year"]== searchYear-1) &
    (fin_rel_search_count_df["purpose"] == "Trade Insurance")]["count"].sum()

recentYearFinancialInstitutionSearchCount = fin_rel_search_count_df[
    (fin_rel_search_count_df["entity_id"]==entity_no) &
    (fin_rel_search_count_df["year"]== searchYear-1) &
    (fin_rel_search_count_df["purpose"] == "Financial Institution")]["count"].sum()

recentYearHirePurchaseLeasingSearchCount = fin_rel_search_count_df[
    (fin_rel_search_count_df["entity_id"]==entity_no) &
    (fin_rel_search_count_df["year"]== searchYear-1) &
    (fin_rel_search_count_df["purpose"] == "Hire Purchase / Leasing")]["count"].sum()

recentYearCommercialSearchCount = comm_rel_search_count_df[
    (comm_rel_search_count_df["entity_id"]==entity_no) &
    (comm_rel_search_count_df["year"]== searchYear-1)]["count"].sum()

recentYearCommercialRetailSearchCount = comm_rel_search_count_df[
    (comm_rel_search_count_df["entity_id"]==entity_no) &
    (comm_rel_search_count_df["year"]== searchYear-1) &
    (comm_rel_search_count_df["purpose"]=="Commercial-Retail")]["count"].sum()

recentYearServicesSearchCount = comm_rel_search_count_df[
    (comm_rel_search_count_df["entity_id"]==entity_no) &
    (comm_rel_search_count_df["year"]== searchYear-1) &
    (comm_rel_search_count_df["purpose"]=="Service")]["count"].sum()

recentYearLegalSearchCount = leg_rel_search_count_df[
    (leg_rel_search_count_df["entity_id"]==entity_no) &
    (leg_rel_search_count_df["year"]== searchYear-1)]["count"].sum()

recentYearLitigationSearchCount = leg_rel_search_count_df[
    (leg_rel_search_count_df["entity_id"]==entity_no) &
    (leg_rel_search_count_df["year"]== searchYear-1) & 
    (leg_rel_search_count_df["purpose"] == "LITIGATION")]["count"].sum()

recentYearConveyancingSearchCount = leg_rel_search_count_df[
    (leg_rel_search_count_df["entity_id"]==entity_no) &
    (leg_rel_search_count_df["year"]== searchYear-1) & 
    (leg_rel_search_count_df["purpose"] == "Conveyancing")]["count"].sum()

print("recentYearFinancialSearchCount: ", recentYearFinancialSearchCount)
print("recentYearTradeInsuranceSearchCount:", recentYearTradeInsuranceSearchCount)
print("recentYearFinancialInstitutionSearchCount: ", recentYearFinancialInstitutionSearchCount)
print("recentYearHirePurchaseLeasingSearchCount: ", recentYearHirePurchaseLeasingSearchCount)

print("recentYearCommercialSearchCount: ", recentYearCommercialSearchCount)
print("recentYearCommercialRetailSearchCount: ", recentYearCommercialRetailSearchCount)
print("recentYearServicesSearchCount: ", recentYearServicesSearchCount)

print("recentYearLegalSearchCount: ", recentYearLegalSearchCount)
print("recentYearLitigationSearchCount: ", recentYearLitigationSearchCount)
print("recentYearConveyancingSearchCount: ", recentYearConveyancingSearchCount)

recentYearFinancialSearchCount:  20
recentYearTradeInsuranceSearchCount: 0
recentYearFinancialInstitutionSearchCount:  0
recentYearHirePurchaseLeasingSearchCount:  8
recentYearCommercialSearchCount:  16
recentYearCommercialRetailSearchCount:  6
recentYearServicesSearchCount:  0
recentYearLegalSearchCount:  8
recentYearLitigationSearchCount:  0
recentYearConveyancingSearchCount:  0

In [75]:
# Preview Add Exp Prop Info dataframe
add_exp_prop_info_df.head()

   entity_id  num_of_employee num_of_commerical_properties_owned
0  01280320E            12572                                 49
1  01879010F            34961                                  -
2  07220850M            33190                                 44
3  11557137X            13537                                 63
4  11955614L            41802                                  -

In [76]:
# Obtain the number of commercial properties owned and employee count

commercialPropertiesOwned = add_exp_prop_info_df[(add_exp_prop_info_df["entity_id"]==entity_no)]["num_of_commerical_properties_owned"].values[0]
employeeCount = add_exp_prop_info_df[(add_exp_prop_info_df["entity_id"]==entity_no)]["num_of_employee"].values[0]

print("commercialPropertiesOwned: ", commercialPropertiesOwned)
print("employeeCount: ", employeeCount)

commercialPropertiesOwned:  49
employeeCount:  12572

In [77]:
# Calculate the revenue per employee and profit per employee

revenuePerEmployee = float(amountOfRevenue) / float(employeeCount)
profitPerEmployee = float(amountOfProfitAfterTax) / float(employeeCount)

print("revenuePerEmployee: ", revenuePerEmployee)
print("profitPerEmployee: ", profitPerEmployee)

revenuePerEmployee:  1830946.2601813553
profitPerEmployee:  1810544.606188355